# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - id: terraform
    name: hashicorp/terraform
    dir: infra/environments/prod
    env:
      - PROJECT_ID=$PROJECT_ID
      - REGION=$_REGION
      - REPO_NAME=$_REPO_NAME
      - REPO_OWNER=$_REPO_OWNER
    script: |
      #!/bin/sh

      terraform init -backend-config="bucket=terraform-${PROJECT_ID}"
      terraform apply -auto-approve -no-color \
        -var project_id=${PROJECT_ID} \
        -var region=${REGION} \
        -var repo_owner=${REPO_OWNER} \
        -var repo_name=${REPO_NAME} \

timeout: 2500s

substitutions:
  _REGION: us-central1
  _REPO_NAME: repo-name
  _REPO_OWNER: repo-owner
